apiVersion: portieris.cloud.ibm.com/v1
kind: ClusterImagePolicy
metadata:
  name: no-vulnerable-images
spec:
  repositories:
   - name: us.icr.io/<my_namespace>/*
      policy:
        vulnerability:
          ICCRVA:
            enabled: true
